### ISSUE TITLE
How to configure caching?

### ISSUE THREAD

**Issue by agonbina** [stormpath/express-stormpath#113] opened 2015-09-26 07:11 UTC
There used to be a section about configuring a cache client(redis in my case) in the docs, not sure what happened to it? I tried all kinds of things, like configuring the ```node-stormpath``` client options, specifically 
```js
{
  api: true,
  client: {
    apiKey: {},
    cacheOptions: {
      store: 'redis',
      host: *****, port: *****, options: { auth_pass: ***** }
    }
  }
}
```
as suggested here: http://docs.stormpath.com/nodejs/api/client#redis, but this doesn't create any connection to my RedisLabs redis instance. 

I also tried the old format(which used to work before): 
```
{
        api: true,
        cache: 'redis',
        cacheHost: config.hostname,
        cachePort: config.port,
        cacheOptions: {
            auth_pass: ''
        }
}
```
Can you please add some sort of documentation about caching, which should be a requirement if you are using Stormpath in a production app?

**Comment by robertjd** [comment] 2015-09-28 18:57
This may be a bug with our new config passing strategy, we will investigate.

**Comment by agonbina** [comment] 2015-10-25 09:45
Hi @robertjd and @typerandom any update on this issue?

**Comment by robbydooo** [comment] 2015-11-02 16:16
I am having the same issue, have tried both the old and new ways of configuring and nothing is working.
Any update?

**Comment by robbydooo** [comment] 2015-11-03 14:51
Just an update on this, no caching is working at all in version 2.1.0. Every request is generating a request back to stormpath adding 800ms-900ms to each request locally, usually they are 4ms. If i disable my internet connection locally it shows me as logged out. renable the connection and I am logged in.

I have tried in memory, redis and memcache and they are all not working.

If I change the redis server to a different IP it does complain that it doesn't exist so it is at least trying to communicate with the cache on bootup.

Any ideas?

Example configuration, although tried many others.

```
var cacheOptions = {
    store: 'redis',
    connection: {
        host: '127.0.0.1',
        port: 6379
    },
    options: {
        return_buffers: false
    },
    ttl: 1200,
    tti: 1200
};

app.use(stormpath.init(app, {
    // Optional configuration options.
    api: true,
    website: true,
    web: {
        logout: {
            enabled: true,
            uri: '/logout',
            nextUri: '/'
        }
    },
    cacheOptions: cacheOptions

}));
```

**Comment by robbydooo** [comment] 2015-11-10 02:40
Another update, if I authenticate with an API key via basic authentication the caching works. However if I authenticate a user using the web forms the caching does not work.

**Comment by robertjd** [comment] 2015-11-11 01:58
Thank you for updating this thread with the reproduction information.  We will need to look into this.  Regarding this issue:

> However if I authenticate a user using the web forms the caching does not work.

That problem will be addressed by #168

**Comment by robertjd** [comment] 2015-11-30 23:18
@agonbina This is a bug in our config parser, I'm now tracking here: https://github.com/stormpath/stormpath-node-config/issues/12

**Comment by typerandom** [comment] 2015-12-27 03:15
Closing since issue should have been resolved around 20 days ago. Reopen if issue still persists.

**Closed by typerandom** 2015-12-27 03:15 UTC
