### ISSUE TITLE
Cannot use my existing redis Client with stormpath.init

### ISSUE THREAD

**Issue by pierredavidbelanger** [stormpath/express-stormpath#129] opened 2015-10-08 20:20 UTC
When I try to reuse my own redis client instance like this:

```javascript
const redis = require('redis').createClient(process.env.REDIS_URL);
...
const stormpath = require('express-stormpath');
app.use(stormpath.init(app, {
    cacheOptions: {
        store: 'redis',
        client: redis
        //connection: {
        //    host: '192.168.99.100',
        //    port: 6379
        //}
    },
    client: {
        apiKey: {
            id: process.env.STORMPATH_API_KEY_ID,
            secret: process.env.STORMPATH_API_KEY_SECRET
        }
    }
}));
```

I get an error like this:
```
node_modules/express-stormpath/node_modules/deep-extend/lib/deep-extend.js:94
var args = Array.prototype.slice.call(arguments, 1);
RangeError: Maximum call stack size exceeded
at module.exports (node_modules/express-stormpath/node_modules/deep-extend/lib/deep-extend.js:94:35)
at node_modules/express-stormpath/node_modules/deep-extend/lib/deep-extend.js:132:19
at Array.forEach (native)
at node_modules/express-stormpath/node_modules/deep-extend/lib/deep-extend.js:104:20
```

Seems like a problem with the `deepExtend(this, options||{});` call in your `function Config(options)` ctor.

When I use the `connection: {}` syntax, it woks.

**Comment by robertjd** [comment] 2015-11-30 23:19
This is a bug in our config parser, I'm now tracking here:

https://github.com/stormpath/stormpath-node-config/issues/12

**Comment by robertjd** [comment] 2015-12-14 17:46
Hello Pierre, this should be fixed in the 2.3.3 release of this library.  Can you please upgrade and let us know if the issue is resolved for your application?  Thanks!

**Comment by pierredavidbelanger** [comment] 2015-12-15 14:13
Bumping express-stormpath to 2.3.3, indeed it works.
Thank you!

**Comment by robertjd** [comment] 2015-12-15 18:59
Awesome!

**Closed by robertjd** 2015-12-15 18:59 UTC
Labels: bug
