### ISSUE TITLE
Server crashes on request with invalid refresh_token cookie

### ISSUE THREAD

**Issue by typerandom** [stormpath/express-stormpath#275] opened 2016-01-21 02:46 UTC
When a server handles a request with an invalid `refresh_token` cookie it crashes with a `Signature verification failed` error.

#### How to reproduce

1. Create an new Node.js server using [this gist](https://gist.github.com/typerandom/8e97e235aaeac1fae840).
2. Start the server.
3. Once `Server listening on http://localhost:3000/` is shown, navigate to [http://localhost:3000/](http://localhost:3000/).
4. Refresh the same page twice.

#### Expected

The message "Invalid refresh token cookie set" should be shown.

#### Actual

The server crashes with the following console output:

```term
(project path)/node_modules/njwt/index.js:60
    throw err;
          ^
JwtParseError: Signature verification failed
```

**Comment by javierbq** [comment] 2016-01-26 05:55
+1

**Comment by javierbq** [comment] 2016-01-29 22:19
@robertjd: what is the meaning of the 'ready' label? is this committed but not released yet?

**Comment by robertjd** [comment] 2016-01-29 22:22
Ready means we've prioritized it over other issues, stay tuned for a fix!

**Comment by javierbq** [comment] 2016-01-29 22:39
awesome thanks!

**Comment by robertjd** [comment] 2016-01-29 22:48
No prob!  FYI, we're using a Waffle board now, that is what is setting the tags.  I need to link to this from our README files:

https://waffle.io/stormpath/express-stormpath

It's pretty amazing

**Comment by javierbq** [comment] 2016-01-29 22:59
Awesome thanks!! We are relying 100% on stormpath for our authentication so I really appreciate the transparency on your development process. 

Related to this particular bug: is there any hack I can do in the meantime to deal with this?

**Comment by robertjd** [comment] 2016-01-30 01:14
Hey @javierbq , I just spent some time with this issue.  Could you share a reproduction case?  I'm not able to reproduce the situation that @typerandom has posted.  I don't get an error with a token that has an invalid signature (Note: I create a new JWT with an invalid signature, I did not use the one that was posted in the repo case above.  That one was giving a different error: token does not exist.)

**Comment by typerandom** [comment] 2016-02-01 08:42
@robertjd I'll look into this a bit more.

**Comment by javierbq** [comment] 2016-02-02 06:52
Hi @robertjd , not sure how to reproduce this bug, I only how to avoid it (deleting the offending cookie).

**Closed** 2016-02-05 22:14 UTC
Labels: bug, needs review
