### ISSUE TITLE
Race condition on startup

### ISSUE THREAD

**Issue by erbridge** [stormpath/express-stormpath#134] opened 2015-10-09 10:27 UTC
This happens occasionally when loading the page soon after starting the server. Running `2.0.10` (was also in `2.0.9`).

```
TypeError: Cannot read property 'authenticateApiRequest' of undefined
    at Object.module.exports [as getUser] (/path/to/project/node_modules/express-stormpath/lib/helpers/get-user.js:186:16)
    at /path/to/project/node_modules/express-stormpath/lib/stormpath.js:80:17
    at /path/to/project/node_modules/async/lib/async.js:689:13
    at iterate (/path/to/project/node_modules/async/lib/async.js:265:13)
    at async.forEachOfSeries.async.eachOfSeries (/path/to/project/node_modules/async/lib/async.js:284:9)
    at _parallel (/path/to/project/node_modules/async/lib/async.js:688:9)
    at Object.async.series (/path/to/project/node_modules/async/lib/async.js:710:9)
    at stormpathMiddleware (/path/to/project/node_modules/express-stormpath/lib/stormpath.js:78:11)
    at Layer.handle [as handle_request] (/path/to/project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/path/to/project/node_modules/express/lib/router/index.js:312:13)
```

**Comment by pierredavidbelanger** [comment] 2015-10-09 10:34
I do not know if it is the right way to fix the problem, but I get rid of this error after waiting for the `stormpath.ready` event before the `app.listen(...)`:

```javascript
app.on('stormpath.ready', function () {
    app.listen(process.env.PORT);
});
```

**Comment by typerandom** [comment] 2015-10-12 09:45
Thanks for reporting it! I'm working on a fix for this.

**Comment by typerandom** [comment] 2015-10-14 12:10
This should be fixed in PR #122.

**Comment by baer** [comment] 2015-11-02 21:33
can this be closed?

**Comment by robertjd** [comment] 2015-11-09 18:03
Hi @baer , this should be resolved now.  Please let us know if something is amiss.

**Closed** 2015-11-09 18:02 UTC
Labels: bug

**Comment by aledotgomez** [comment] 2015-12-17 16:17
Hi, I have an app hosted on heroku that initially loads with the same error as above, but then is fixed after a refresh. Is there a way to add the stormpath.ready method on an app created through the express-generator? If I add the callback -
 ```
app.on('stormpath.ready', function () {
    app.listen(process.env.PORT);
});
```
It gives me an error on Heroku deploy. Thank you.

**Comment by robertjd** [comment] 2015-12-17 17:07
Hi @aledotgomez , can you show us the error that you are getting?  I'd also like to know which generator you are using?  My guess is that something inside of the generated code is trying to call `app.listen()` for you, which interferes with the one that you are trying to add.  Thanks!

**Comment by aledotgomez** [comment] 2015-12-17 17:34
The generator I'm using is [express-generator](https://www.npmjs.com/package/express-generator).
I'm guessing that listening to the port from the Heroku environment is irrelevant, but I don't know what to start the stormpath method on. 
The error trace from `heroku logs` is the following:
```
015-12-17T17:24:08.079058+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-17T17:24:08.023538+00:00 app[web.1]: events.js:141
2015-12-17T17:24:08.023706+00:00 app[web.1]:       ^
2015-12-17T17:24:08.023670+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2015-12-17T17:24:08.023717+00:00 app[web.1]: 
2015-12-17T17:24:08.023731+00:00 app[web.1]: Error: listen EADDRINUSE :::38560
2015-12-17T17:24:08.023732+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-17T17:24:08.023734+00:00 app[web.1]:     at Server._listen2 (net.js:1234:14)
2015-12-17T17:24:08.023733+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-17T17:24:08.023736+00:00 app[web.1]:     at Server.listen (net.js:1366:5)
2015-12-17T17:24:08.023737+00:00 app[web.1]:     at EventEmitter.listen (/app/node_modules/express/lib/application.js:617:24)
2015-12-17T17:24:08.023735+00:00 app[web.1]:     at listen (net.js:1270:10)
2015-12-17T17:24:08.023738+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/app.js:93:9)
2015-12-17T17:24:08.023738+00:00 app[web.1]:     at emitNone (events.js:67:13)
2015-12-17T17:24:08.023742+00:00 app[web.1]:     at Object.wrapGetResourceResponse [as _wrapGetResourceResponse] (/app/node_modules/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:89:12)
2015-12-17T17:24:08.023739+00:00 app[web.1]:     at EventEmitter.emit (events.js:166:7)
2015-12-17T17:24:08.023740+00:00 app[web.1]:     at /app/node_modules/express-stormpath/lib/stormpath.js:214:11
2015-12-17T17:24:08.023743+00:00 app[web.1]:     at onGetResourceRequestResult (/app/node_modules/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:278:13)
2015-12-17T17:24:08.023744+00:00 app[web.1]:     at Request.onRequestResult [as _callback] (/app/node_modules/express-stormpath/node_modules/stormpath/lib/ds/RequestExecutor.js:110:7)
2015-12-17T17:24:08.023745+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/express-stormpath/node_modules/request/request.js:198:22)
2015-12-17T17:24:08.023746+00:00 app[web.1]:     at emitTwo (events.js:87:13)
2015-12-17T17:24:08.023746+00:00 app[web.1]:     at Request.emit (events.js:172:7)
2015-12-17T17:24:08.023750+00:00 app[web.1]:     at emitNone (events.js:72:20)
2015-12-17T17:24:08.023748+00:00 app[web.1]:     at Request.emit (events.js:169:7)
2015-12-17T17:24:08.023748+00:00 app[web.1]:     at emitOne (events.js:82:20)
2015-12-17T17:24:08.023747+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/express-stormpath/node_modules/request/request.js:1035:10)
2015-12-17T17:24:08.069569+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-17T17:24:08.023749+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/express-stormpath/node_modules/request/request.js:962:12)
2015-12-17T17:24:08.023760+00:00 app[web.1]:     at IncomingMessage.emit (events.js:166:7)
2015-12-17T17:24:08.069736+00:00 app[web.1]: npm ERR! node v5.1.1
2015-12-17T17:24:08.070756+00:00 app[web.1]: npm ERR! code ELIFECYCLE
```
Thanks again for your help.

**Comment by rdegges** [comment] 2015-12-17 17:55
Heyo, the issue is not a Stormpath issue -- what's happening is that your application is not listening on the correct port. Heroku requires you to listen on a port that is randomly defined in the PORT environment variable.

For instance:

```javascript
app.listen(process.env.PORT);
```

express-generator doesn't do this by default.

**Comment by robertjd** [comment] 2015-12-18 21:40
@rdegges the boilerplate from the generator does do that by default:

https://github.com/expressjs/generator/blob/b313f3ba2779b9935212d204c3066be83a3aeab9/templates/js/www#L15

@aledotgomez can you search your code to ensure that you don't have multiple calls to `app.listen` or `server.listen` ?  Thanks!

**Comment by aledotgomez** [comment] 2015-12-18 22:56
hey @robertjd there is no other  `app,listen` or `server.listen` calls in my code. I'm thinking of going into the express module and placing the following call:
```
app.on('stormpath.ready', function () {
    app.listen(process.env.PORT);
});
```
where the app object is initialized. Any alternatives from changing the module directly?  Thanks. @rdegges  @robertjd

**Comment by tsgautier** [comment] 2016-01-14 00:15
@robertjd I've just gone through the tutorial listed here:

https://stormpath.com/blog/angular-node-15-minutes/

And received the same error.  Changing the express startup line to:

app.on('stormpath.ready', startServer);

As mentioned in the bug report fixes the issue.  The version of express-stormpath I am using express-stormpath 2.3.5.

**Comment by ziggamon** [comment] 2016-01-28 22:36
Using the keystone.js framework and it seems like i doesn't let you do custom code for app.listen (or at least I didn't manage to find it).

Suggestions on how to get this working without this race issue? (Putting all of keystone.start() in stormpath.ready event seems to break deployment on heroku). Have spent some hours now pulling both libraries apart to see if it can be interwoven but to no success. 

Worked fine with express-stormpath 1.x.

Advice welcome.

**Comment by tungpham** [comment] 2016-03-11 21:16
Can confirm. I'm seeing the same issue with epxress-generator, express-stormpath hosting on heroku
