### ISSUE TITLE
BodyParser breaks registration in 3.1.2

### ISSUE THREAD

**Issue by AlstonLin** [stormpath/express-stormpath#442] opened 2016-06-11 04:42 UTC
Specifically, adding `app.use(bodyParser.json());` causes any Registration attempts to fail and giving a message "First Name required." from the server.

Probably related to #436

**Comment by edjiang** [comment] 2016-06-11 18:28
Hey Alston,

For the meantime, you can put bodyParser after `app.use(stormpath.init(app, {...}))` and it should work

**Comment by AlstonLin** [comment] 2016-06-11 20:31
Putting bodyParser after the init line works. Thanks!

**Comment by robertjd** [comment] 2016-06-13 21:40
Thanks all, I'm closing this as s duplicate of #436

**Closed by robertjd** 2016-06-13 21:40 UTC
