### ISSUE TITLE
expand customData has stopped working in 2.3.3

### ISSUE THREAD

**Issue by Jonlee2001** [stormpath/express-stormpath#240] opened 2015-12-17 14:27 UTC
Hi,
I've just upgraded from 2.2 to 2.3.3 and the settings for expand: { customData: true} have stopped working.
Any ideas if mine is an isolated case? Also I see that this issue has been raised for earlier versions (2.0.9) but is now marked in fixed - but there's nothing against version 2.3.3.

Any help gratefully received,

Jon

**Comment by Jonlee2001** [comment] 2015-12-17 14:40
I've just done another test and it's not limited to customData - it appears that anything you put in the "expand" section of the app config gets ignored (groups, apiKeys, directory, etc.)

**Comment by robertjd** [comment] 2015-12-17 19:36
Hi Jon, could you show us how you are using `stormpath.int()` so that we can ensure the option format is correct?  For reference, please see our example project:

https://github.com/stormpath/express-stormpath-sample-project

It is configured to expand custom data, and I can confirm that this is true by visiting the `/me` route after I login.

Thanks!

**Comment by Jonlee2001** [comment] 2015-12-18 12:58
Hi Robert,
Here's my init function:
```
app.use(stormpath.init(app,{
  postRegistrationHandler: function (account, req, res, next) {
    account.getCustomData(function(err, data) {
      if (err)
        return next(err);
      request.get(app.locals.pmmsApiUrl + "supplier/authenticate/" + data.authenticationKey, function(err, resp, body){
        if (err)
          return next(err);
        data['Company'] = JSON.parse(body);
        data['Company'].username = data['Company'].name.toLowerCase().replace(/ /g, '');
        data.save();
        console.log("Registration Successful! " + data['Company']);
        next();
      });

   });

  },
  application: {
      href: process.env.STORMPATH_URL
    },
 website: true,
 web: {
   login: {
     enabled: true,
     view: path.join(__dirname,'views','login.jade'),
     nextUri: '/dashboard'
   },
   register: {
     view: path.join(__dirname,'views','register.jade'),
     fields: {
      authenticationKey: {
        enabled: true,
        label: 'Supplier Code',
        name: 'authenticationKey',
        placeholder: '(8 Digit unique supplier code)',
        required: true,
        type: 'text'
      }
   }
 },
 client: {
    apiKey: {
      id: process.env.STORMPATH_API_KEY_ID,
      secret: process.env.STORMPATH_API_KEY_SECRET
    }
  },
  expand: {
    customData: true
  },

}}));
```
I've checked against the sample project and it looks the same to me.
Jon

**Comment by Jonlee2001** [comment] 2015-12-18 14:15
Eureka! I've just moved the "website: true" and "expand: {}" sections to the top of the init function and it works! However it's not clear in the documentation that the order of the sections is important - perhaps this should be updated.

**Comment by robertjd** [comment] 2015-12-18 21:09
Hmm that's pretty odd!  Where was it that you were seeing the account without the expanded data?  I just tried you init function in our sample app, and was no able to change the behaviour of the `/me` route by changing the order of the properties

**Comment by typerandom** [comment] 2015-12-27 03:17
Closing since this just seems like a configuration issue. Order in configuration doesn't play any significant role (i.e. it's just key lookups, not index).

**Closed by typerandom** 2015-12-27 03:17 UTC
